---
- name: Check to see if the user limits have already been deployed
  stat:
    path: /etc/security/limits.d/couchbase-server.conf
  register: check_limits
  tags:
    - couchbase_os
    - couchbase_user_limits

- name: Make sure the limits directory exists
  become: yes
  become_user: root
  file:
    dest: /etc/security/limits.d
    state: directory
  when: check_limits.stat.exists == False
  tags:
    - couchbase_os
    - couchbase_user_limits

- name: User limits config
  become: yes
  become_user: root
  template:
    src: etc/security/limits.d/couchbase-server.conf.j2
    dest: /etc/security/limits.d/couchbase-server.conf
    owner: root
    group: root
    mode: 0644
  when: check_limits.stat.exists == False
  tags:
    - couchbase_os
    - couchbase_user_limits
